import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FA",
  },
  
  navbar: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 45,
    paddingBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#5B21B6',
    elevation: 8,
    shadowColor: '#5B21B6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  navTitle: {
    color: '#fff',
    fontSize: 23,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
    letterSpacing: 0.8,
  },
  settingsButton: {
    padding: 6,
    borderRadius: 8,
  },
  
  grid: {
    justifyContent: 'center',
    padding: 20,
    paddingTop: 25,
    gap: 15,
  },
  card: {
    width: (width - 70) / 2,
    margin: 7,
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 25,
    alignItems: 'center',
    justifyContent: 'center',
    height: (width - 70) / 2,
    elevation: 4,
    shadowColor: "#5B21B6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(91, 33, 182, 0.08)',
  },
  cardIcon: {
    marginBottom: 15,
    color: "#5B21B6",
  },
  iconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#EDE9FE',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardText: {
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    color: '#2C3E50',
    letterSpacing: 0.5,
  },
  
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  modalBox: {
    width: '88%',
    maxWidth: 400,
    padding: 35,
    backgroundColor: '#fff',
    borderRadius: 24,
    alignItems: 'center',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: 25,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    marginTop: 10,
    color: '#5B21B6',
    letterSpacing: 0.8,
  },
  modalBtn: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    backgroundColor: '#5B21B6',
    borderRadius: 14,
    marginBottom: 14,
    elevation: 4,
    shadowColor: '#5B21B6',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    gap: 10,
  },
  modalBtnText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  logoutBtn: {
    backgroundColor: '#EF4444',
  },
  modalClose: {
    marginTop: 18,
    padding: 10,
  },
  modalCloseTxt: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '600',
  },

  modalContent: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: '#fff',
    padding: 35,
    borderRadius: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  alertIconContainer: {
    marginBottom: 20,
  },
  modalText: {
    fontSize: 17,
    fontWeight: '500',
    color: '#2C3E50',
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 10,
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 30,
    gap: 14,
  },
  modalBotao: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  modalBotaoCancelar: {
    backgroundColor: '#64748B',
  },
  modalBotaoConfirmar: {
    backgroundColor: '#EF4444',
  },
  modalBotaoTexto: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  
  backBtn: {
    position: 'absolute',
    top: 48,
    left: 15,
    padding: 10,
    zIndex: 10,
    backgroundColor: '#FFF',
    borderRadius: 50,
    elevation: 6,
    shadowColor: '#5B21B6',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  contentWithMargin: {
    flex: 1,
    padding: 20,
    paddingTop: 10,
  },
});